[workspace]
resolver = "2"
members = ["metadata", "playground", "runtime", "runtime-binding-gen", "sbg", "nativescript", "typings-generator", "integration-tests", "runtime-devtools", "metadata-generator","tools/dotnet-tool"]

[workspace.dependencies]
windows = "0.62.2"

[profile.dev]
debug = true

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
debug = false
incremental = false
strip = true

# Release build with development tools and SBG (Static Binding Generator)
[profile.release-with-devtools]
inherits = "release"
