[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
byteorder = "1.5"
regex = "1.10"
anyhow = "1.0"
libffi = "5.1.0"
v8 = "147"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2"
form_urlencoded = "1"
metadata = { path = "../metadata" }
runtime-binding-gen = { path = "../runtime-binding-gen" }
parking_lot = "0.12"
libc = "0.2"

[dependencies.windows]
workspace = true
features = [
    "Foundation",
    "Foundation_Collections",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_EventLog",
    "Win32_Security",
    "Win32_System_Ole",
    "Win32_System_Threading",
    "Win32_System_WinRT",
    "Win32_System_WindowsProgramming",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Dwm",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Data_Json",
]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "sync_runtime"
harness = false

[[bench]]
name = "async_runtime"
harness = false