use anyhow::{Context, Result};
use clap::Parser as ClapParser;
use glob::glob;
use serde::Serialize;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use oxc_allocator::Allocator;
use oxc_ast::ast::*;
use oxc_parser::Parser as OxcParser;
use oxc_span::SourceType;

#[derive(ClapParser)]
#[command(
    author,
    version,
    about = "dotnet-tool: scan JS bundles for WinRT extensions and write sbg_metadata.json"
)]
struct Args {
    #[arg(long, default_value = ".")]
    app_root: String,

    #[arg(long, default_value = "app")]
    dir: String,

    /// Glob pattern(s) for bundle files to scan. Separate multiple patterns with ';'.
    #[arg(long, default_value = "**/*.js;**/*.mjs;**/*.cjs")]
    pattern: String,

    #[arg(long, default_value_t = false)]
    force: bool,

    #[arg(long)]
    sbg_output: Option<String>,
}

#[derive(Serialize)]
struct SbgMethod {
    name: String,
    #[serde(rename = "returnType")]
    return_type: String,
    parameters: Vec<[String; 2]>,
    modifier: String,
}

#[derive(Serialize)]
struct SbgEntry {
    #[serde(rename = "typeName")]
    type_name: String,
    #[serde(rename = "baseType")]
    base_type: String,
    methods: Vec<SbgMethod>,
    properties: Vec<String>,
    interfaces: Vec<String>,
    #[serde(rename = "isAutoGeneratedName")]
    is_auto_generated_name: bool,
}

#[derive(Default, Clone)]
struct DetectedExtension {
    #[allow(dead_code)]
    js_name: String,
    base_type: String,
    proxy_name: Option<String>,
    methods: Vec<String>,
    interfaces: Vec<String>,
}

fn is_winrt_type(s: &str) -> bool {
    s.contains('.')
        && s.split('.')
            .any(|seg| seg.starts_with(|c: char| c.is_uppercase()))
}

fn build_sbg_entries(extensions: &[DetectedExtension]) -> Vec<SbgEntry> {
    let mut counter: u32 = 0;
    let mut seen: HashMap<String, bool> = HashMap::new();
    let mut out = Vec::new();
    for ext in extensions {
        let key = format!(
            "{}|{}",
            ext.base_type,
            ext.proxy_name.as_deref().unwrap_or("")
        );
        if seen.contains_key(&key) {
            continue;
        }
        seen.insert(key, true);

        let (type_name, is_auto) = match &ext.proxy_name {
            Some(n) if !n.is_empty() => (n.clone(), false),
            _ => {
                counter += 1;
                let short = ext.base_type.split('.').next_back().unwrap_or("Object");
                (format!("NativeScript.Gen.{}_{}", short, counter), true)
            }
        };

        // Pass every detected override name through unfiltered — real signatures (return type,
        // parameters, modifier) are resolved from WinRT metadata by `sbg` at generation time
        // (see `sbg::signature_resolver`), which knows how to look up ANY base type's virtual,
        // not just a hardcoded handful. These placeholder values are overwritten there; a method
        // sbg can't resolve is skipped (with a warning) rather than emitted with a guessed and
        // likely-wrong signature.
        let methods = ext
            .methods
            .iter()
            .map(|name| SbgMethod {
                name: name.clone(),
                return_type: "Void".to_string(),
                parameters: Vec::new(),
                modifier: "public override".to_string(),
            })
            .collect();

        out.push(SbgEntry {
            type_name,
            base_type: ext.base_type.clone(),
            methods,
            properties: Vec::new(),
            interfaces: ext.interfaces.clone(),
            is_auto_generated_name: is_auto,
        });
    }
    out
}

fn main() -> Result<()> {
    let args = Args::parse();

    let scan_dir_candidate = PathBuf::from(&args.app_root).join(&args.dir);
    let scan_dir = if scan_dir_candidate.exists() {
        scan_dir_candidate
    } else {
        PathBuf::from(&args.app_root)
    };
    let scan_dir_str = scan_dir.to_string_lossy().replace('\\', "/");

    let mut all_extensions: Vec<DetectedExtension> = Vec::new();
    let mut has_dotnet = false;

    for pat in args.pattern.split(';') {
        let glob_pattern = format!("{}/{}", scan_dir_str, pat.trim());
        for entry in glob(&glob_pattern).context("glob pattern failed")? {
            let path = entry?;
            let content = match fs::read_to_string(&path) {
                Ok(s) => s,
                Err(_) => continue,
            };
            if scan_file_ast(&content, &mut all_extensions) {
                has_dotnet = true;
            }
        }
    }

    let sbg_output_dir = args
        .sbg_output
        .as_deref()
        .map(PathBuf::from)
        .or_else(|| std::env::var("SBG_OUTPUT_DIR").ok().map(PathBuf::from));

    if let Some(dir) = &sbg_output_dir {
        if !all_extensions.is_empty() {
            let entries = build_sbg_entries(&all_extensions);
            fs::create_dir_all(dir)?;
            let json = serde_json::to_string_pretty(&entries)?;
            let out_path = dir.join("sbg_metadata.json");
            fs::write(&out_path, &json)?;
            eprintln!(
                "[dotnet-tool] Wrote {} extension(s) to {}",
                entries.len(),
                out_path.display()
            );
        } else {
            eprintln!("[dotnet-tool] No WinRT extensions found; sbg_metadata.json not written");
        }
    }

    if has_dotnet || !all_extensions.is_empty() || args.force {
        if let Err(e) = publish_and_copy_bridge(PathBuf::from(&args.app_root)) {
            eprintln!("Warning: failed to publish/copy dotnet-bridge: {}", e);
        } else {
            eprintln!("[dotnet-tool] dotnet-bridge published");
        }
    }

    Ok(())
}

// ── AST Scanner ───────────────────────────────────────────────────────────────

#[derive(Default)]
struct ScanCtx {
    iife_map: HashMap<String, String>,
    decorate_map: HashMap<String, (Option<String>, Vec<String>)>,
    method_map: HashMap<String, Vec<String>>,
    extensions: Vec<DetectedExtension>,
    has_dotnet: bool,
}

impl ScanCtx {
    fn finalize(mut self, out: &mut Vec<DetectedExtension>) -> bool {
        for (child, base) in self.iife_map {
            let (proxy, ifaces) = self.decorate_map.remove(&child).unwrap_or_default();
            let methods = self.method_map.remove(&child).unwrap_or_default();
            out.push(DetectedExtension {
                js_name: child,
                base_type: base,
                proxy_name: proxy,
                methods,
                interfaces: ifaces,
            });
        }
        out.extend(self.extensions);
        self.has_dotnet
    }
}

fn scan_file_ast(content: &str, out: &mut Vec<DetectedExtension>) -> bool {
    let allocator = Allocator::default();
    let source_type = SourceType::cjs();
    let ret = OxcParser::new(&allocator, content, source_type).parse();
    let mut ctx = ScanCtx::default();
    walk_stmts(&ret.program.body, &mut ctx);
    ctx.finalize(out)
}

fn walk_stmts<'a>(stmts: &oxc_allocator::Vec<'a, Statement<'a>>, ctx: &mut ScanCtx) {
    for stmt in stmts {
        walk_stmt(stmt, ctx);
    }
}

fn walk_stmt<'a>(stmt: &Statement<'a>, ctx: &mut ScanCtx) {
    match stmt {
        Statement::VariableDeclaration(decl) => {
            for d in &decl.declarations {
                if let Some(init) = &d.init {
                    if let BindingPattern::BindingIdentifier(id) = &d.id {
                        if let Some(base) = extract_iife_base(init) {
                            ctx.iife_map.insert(id.name.to_string(), base);
                        }
                    }
                    walk_expr(init, ctx);
                }
            }
        }
        Statement::ExpressionStatement(expr_stmt) => {
            walk_expr(&expr_stmt.expression, ctx);
        }
        Statement::BlockStatement(block) => {
            walk_stmts(&block.body, ctx);
        }
        Statement::FunctionDeclaration(func) => {
            if let Some(body) = &func.body {
                walk_stmts(&body.statements, ctx);
            }
        }
        Statement::IfStatement(s) => {
            walk_expr(&s.test, ctx);
            walk_stmt(&s.consequent, ctx);
            if let Some(alt) = &s.alternate {
                walk_stmt(alt, ctx);
            }
        }
        Statement::WhileStatement(s) => {
            walk_expr(&s.test, ctx);
            walk_stmt(&s.body, ctx);
        }
        Statement::DoWhileStatement(s) => {
            walk_stmt(&s.body, ctx);
            walk_expr(&s.test, ctx);
        }
        Statement::ForStatement(s) => {
            if let Some(ForStatementInit::VariableDeclaration(decl)) = &s.init {
                for d in &decl.declarations {
                    if let Some(init) = &d.init {
                        walk_expr(init, ctx);
                    }
                }
            }
            if let Some(test) = &s.test {
                walk_expr(test, ctx);
            }
            walk_stmt(&s.body, ctx);
        }
        Statement::ForInStatement(s) => {
            walk_expr(&s.right, ctx);
            walk_stmt(&s.body, ctx);
        }
        Statement::ForOfStatement(s) => {
            walk_expr(&s.right, ctx);
            walk_stmt(&s.body, ctx);
        }
        Statement::ReturnStatement(s) => {
            if let Some(arg) = &s.argument {
                walk_expr(arg, ctx);
            }
        }
        Statement::LabeledStatement(s) => {
            walk_stmt(&s.body, ctx);
        }
        Statement::TryStatement(s) => {
            walk_stmts(&s.block.body, ctx);
            if let Some(handler) = &s.handler {
                walk_stmts(&handler.body.body, ctx);
            }
            if let Some(finalizer) = &s.finalizer {
                walk_stmts(&finalizer.body, ctx);
            }
        }
        Statement::SwitchStatement(s) => {
            for case in &s.cases {
                walk_stmts(&case.consequent, ctx);
            }
        }
        _ => {}
    }
}

fn walk_expr<'a>(expr: &Expression<'a>, ctx: &mut ScanCtx) {
    match expr {
        Expression::CallExpression(call) => {
            check_call(call, ctx);
            walk_expr(&call.callee, ctx);
            for arg in &call.arguments {
                walk_arg(arg, ctx);
            }
        }
        Expression::FunctionExpression(func) => {
            if let Some(body) = &func.body {
                walk_stmts(&body.statements, ctx);
            }
        }
        Expression::ArrowFunctionExpression(arrow) => {
            walk_stmts(&arrow.body.statements, ctx);
        }
        Expression::ObjectExpression(obj) => {
            for prop in &obj.properties {
                if let ObjectPropertyKind::ObjectProperty(p) = prop {
                    walk_expr(&p.value, ctx);
                }
            }
        }
        Expression::StaticMemberExpression(sme) => {
            walk_expr(&sme.object, ctx);
        }
        Expression::ParenthesizedExpression(p) => {
            walk_expr(&p.expression, ctx);
        }
        Expression::SequenceExpression(seq) => {
            for e in &seq.expressions {
                walk_expr(e, ctx);
            }
        }
        Expression::AssignmentExpression(assign) => {
            // Detect Foo.prototype.Method = function(...) {} inside IIFE bodies.
            if let AssignmentTarget::StaticMemberExpression(outer) = &assign.left {
                if let Expression::StaticMemberExpression(inner) = &outer.object {
                    if inner.property.name == "prototype" {
                        if let Expression::Identifier(class_id) = &inner.object {
                            let class_name = class_id.name.as_str();
                            if ctx.iife_map.contains_key(class_name) {
                                let is_fn = matches!(
                                    assign.right.get_inner_expression(),
                                    Expression::FunctionExpression(_)
                                        | Expression::ArrowFunctionExpression(_)
                                );
                                if is_fn {
                                    ctx.method_map
                                        .entry(class_name.to_string())
                                        .or_default()
                                        .push(outer.property.name.to_string());
                                }
                            }
                        }
                    }
                }
            }
            walk_expr(&assign.right, ctx);
        }
        Expression::LogicalExpression(log) => {
            walk_expr(&log.left, ctx);
            walk_expr(&log.right, ctx);
        }
        Expression::ConditionalExpression(cond) => {
            walk_expr(&cond.test, ctx);
            walk_expr(&cond.consequent, ctx);
            walk_expr(&cond.alternate, ctx);
        }
        Expression::UnaryExpression(unary) => {
            walk_expr(&unary.argument, ctx);
        }
        _ => {}
    }
}

fn walk_arg<'a>(arg: &Argument<'a>, ctx: &mut ScanCtx) {
    match arg {
        Argument::SpreadElement(s) => walk_expr(&s.argument, ctx),
        Argument::CallExpression(call) => {
            check_call(call, ctx);
            walk_expr(&call.callee, ctx);
            for a in &call.arguments {
                walk_arg(a, ctx);
            }
        }
        Argument::FunctionExpression(func) => {
            if let Some(body) = &func.body {
                walk_stmts(&body.statements, ctx);
            }
        }
        Argument::ArrowFunctionExpression(arrow) => {
            walk_stmts(&arrow.body.statements, ctx);
        }
        Argument::StaticMemberExpression(sme) => {
            walk_expr(&sme.object, ctx);
        }
        Argument::SequenceExpression(seq) => {
            for e in &seq.expressions {
                walk_expr(e, ctx);
            }
        }
        Argument::AssignmentExpression(assign) => {
            walk_expr(&assign.right, ctx);
        }
        Argument::ParenthesizedExpression(p) => {
            walk_expr(&p.expression, ctx);
        }
        _ => {}
    }
}

fn check_call<'a>(call: &CallExpression<'a>, ctx: &mut ScanCtx) {
    match call.callee.get_inner_expression() {
        Expression::Identifier(id) => match id.name.as_str() {
            "__decorate" => handle_decorate(call, ctx),
            _ => {}
        },
        Expression::StaticMemberExpression(sme) => {
            let prop = sme.property.name.as_str();
            match prop {
                "extend" | "extendManaged" => {
                    if let Some(base) = expr_to_dotted(&sme.object) {
                        if is_winrt_type(&base) {
                            handle_extend(&base, call, ctx);
                        }
                    }
                }
                "invokeMethod" | "invokeMethodAsync" => {
                    if let Expression::Identifier(obj) = &sme.object {
                        if obj.name == "DotNet" {
                            ctx.has_dotnet = true;
                        }
                    }
                }
                _ => {}
            }
        }
        _ => {}
    }
}

fn handle_decorate<'a>(call: &CallExpression<'a>, ctx: &mut ScanCtx) {
    if call.arguments.len() < 2 {
        return;
    }
    let class_name = match &call.arguments[1] {
        Argument::Identifier(id) => id.name.to_string(),
        _ => return,
    };
    let decorators = match &call.arguments[0] {
        Argument::ArrayExpression(arr) => arr,
        _ => return,
    };

    let mut proxy_name: Option<String> = None;
    let mut interfaces: Vec<String> = Vec::new();

    for elem in &decorators.elements {
        let deco_call = match elem {
            ArrayExpressionElement::CallExpression(c) => c,
            _ => continue,
        };
        let deco_name = match deco_call.callee.get_inner_expression() {
            Expression::Identifier(id) => id.name.as_str().to_string(),
            _ => continue,
        };
        match deco_name.as_str() {
            "CSharpProxy" => {
                if let Some(Argument::StringLiteral(s)) = deco_call.arguments.first() {
                    proxy_name = Some(s.value.to_string());
                }
            }
            "NativeClass" => {
                // @NativeClass() — use the JS class name as the C# type name.
                // CSharpProxy takes precedence if both decorators are present.
                if proxy_name.is_none() {
                    proxy_name = Some(format!("NativeScript.Gen.{}", class_name));
                }
            }
            "Interfaces" => {
                if let Some(Argument::ArrayExpression(arr)) = deco_call.arguments.first() {
                    for iface_elem in &arr.elements {
                        if let Some(s) = array_elem_to_dotted(iface_elem) {
                            if is_winrt_type(&s) {
                                interfaces.push(s);
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }

    ctx.decorate_map
        .insert(class_name, (proxy_name, interfaces));
}

fn handle_extend<'a>(base_type: &str, call: &CallExpression<'a>, ctx: &mut ScanCtx) {
    let args = &call.arguments;
    let (proxy_name, obj) = match args.as_slice() {
        [Argument::StringLiteral(name), Argument::ObjectExpression(body)] => {
            (Some(name.value.to_string()), Some(body.as_ref()))
        }
        [Argument::ObjectExpression(body)] => (None, Some(body.as_ref())),
        _ => (None, None),
    };
    let methods = obj.map(methods_from_obj).unwrap_or_default();
    let interfaces = obj.map(interfaces_from_obj).unwrap_or_default();
    ctx.extensions.push(DetectedExtension {
        js_name: String::new(),
        base_type: base_type.to_string(),
        proxy_name,
        methods,
        interfaces,
    });
}

fn extract_iife_base<'a>(init: &Expression<'a>) -> Option<String> {
    let inner = init.get_inner_expression();
    let Expression::CallExpression(call) = inner else {
        return None;
    };
    let callee = call.callee.get_inner_expression();
    if !matches!(callee, Expression::FunctionExpression(_)) {
        return None;
    }
    if call.arguments.len() != 1 {
        return None;
    }
    match &call.arguments[0] {
        Argument::StaticMemberExpression(sme) => member_to_dotted(sme).filter(|s| is_winrt_type(s)),
        Argument::Identifier(id) => {
            let s = id.name.to_string();
            if is_winrt_type(&s) {
                Some(s)
            } else {
                None
            }
        }
        _ => None,
    }
}

fn expr_to_dotted<'a>(expr: &Expression<'a>) -> Option<String> {
    match expr.get_inner_expression() {
        Expression::Identifier(id) => Some(id.name.to_string()),
        Expression::StaticMemberExpression(sme) => member_to_dotted(sme),
        _ => None,
    }
}

fn member_to_dotted<'a>(sme: &StaticMemberExpression<'a>) -> Option<String> {
    let base = expr_to_dotted(&sme.object)?;
    Some(format!("{}.{}", base, sme.property.name))
}

fn array_elem_to_dotted<'a>(elem: &ArrayExpressionElement<'a>) -> Option<String> {
    match elem {
        ArrayExpressionElement::StaticMemberExpression(sme) => member_to_dotted(sme),
        ArrayExpressionElement::Identifier(id) => Some(id.name.to_string()),
        _ => None,
    }
}

fn methods_from_obj<'a>(obj: &ObjectExpression<'a>) -> Vec<String> {
    obj.properties
        .iter()
        .filter_map(|prop| {
            let ObjectPropertyKind::ObjectProperty(p) = prop else {
                return None;
            };
            let is_fn = p.method
                || matches!(
                    &p.value,
                    Expression::FunctionExpression(_) | Expression::ArrowFunctionExpression(_)
                );
            if !is_fn {
                return None;
            }
            let name = match &p.key {
                PropertyKey::StaticIdentifier(id) => id.name.as_str().to_string(),
                PropertyKey::StringLiteral(s) => s.value.to_string(),
                _ => return None,
            };
            if matches!(name.as_str(), "constructor" | "interfaces" | "init") {
                return None;
            }
            Some(name)
        })
        .collect()
}

fn interfaces_from_obj<'a>(obj: &ObjectExpression<'a>) -> Vec<String> {
    for prop in &obj.properties {
        let ObjectPropertyKind::ObjectProperty(p) = prop else {
            continue;
        };
        let key_name = match &p.key {
            PropertyKey::StaticIdentifier(id) => id.name.as_str(),
            _ => continue,
        };
        if key_name != "interfaces" {
            continue;
        }
        let Expression::ArrayExpression(arr) = &p.value else {
            continue;
        };
        return arr
            .elements
            .iter()
            .filter_map(array_elem_to_dotted)
            .filter(|s| is_winrt_type(s))
            .collect();
    }
    Vec::new()
}

// ── Bridge Publishing ─────────────────────────────────────────────────────────

fn publish_and_copy_bridge(app_root: PathBuf) -> Result<()> {
    let bridge_dir = find_bridge_dir(&app_root).ok_or_else(|| {
        anyhow::anyhow!("dotnet-bridge not found (searched up to 6 levels from app_root)")
    })?;

    // The generated Windows project already consumes dotnet-bridge from the
    // located bridge directory itself (for example platforms/windows/dotnet-bridge).
    // Writing the publish output marker under the app project directory
    // (for example platforms/windows/toolbox/dotnet-bridge) creates a second,
    // stale location that the build does not use.
    let publish_dir = bridge_dir.join("publish");

    let status = std::process::Command::new("dotnet")
        .args([
            "publish",
            "-c",
            "Release",
            "-o",
            "publish",
            "-p:CopyLocalLockFileAssemblies=true",
        ])
        .current_dir(&bridge_dir)
        .status()
        .context("failed to spawn dotnet publish; ensure .NET SDK is installed")?;

    if !status.success() {
        anyhow::bail!("dotnet publish failed with exit code: {:?}", status.code());
    }

    if !publish_dir.exists() {
        anyhow::bail!(
            "dotnet publish did not produce a publish/ folder at {}",
            publish_dir.display()
        );
    }

    let marker = publish_dir.join(".dotnet_tool_done");
    fs::write(&marker, "dotnet-tool-published")
        .with_context(|| format!("failed to write marker at {}", marker.display()))?;
    Ok(())
}

fn find_bridge_dir(start: &PathBuf) -> Option<PathBuf> {
    let mut cur = start.clone();
    for _ in 0..6 {
        let candidate = cur.join("dotnet-bridge");
        if candidate.join("DotNetBridge.csproj").exists() {
            return Some(candidate);
        }
        if !cur.pop() {
            break;
        }
    }
    None
}
