using System;
using System.Buffers;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Globalization;

namespace NativeScriptBridge;

public static partial class Bridge
{
    // Cache for dynamically generated proxy types (dev-only fallback).
    private static readonly ConcurrentDictionary<Type, Type> s_dynamicProxyCache = new();
    private static readonly AssemblyBuilder? s_dynamicAssembly = CreateDynamicAssembly();
    private static readonly ModuleBuilder? s_dynamicModule   = CreateDynamicModule(s_dynamicAssembly);

    private static AssemblyBuilder? CreateDynamicAssembly()
    {
        try
        {
            var an = new AssemblyName("NSWinRTDynamicProxies");
            var asm = AssemblyBuilder.DefineDynamicAssembly(an, AssemblyBuilderAccess.Run);
            
            return asm;
        }
        catch { return null; }
    }

    private static ModuleBuilder? CreateDynamicModule(AssemblyBuilder? asm)
    {
            try {
                var m = asm?.DefineDynamicModule("NSWinRTDynamicProxiesModule");
                return m;
            } catch { return null; }
    }

    // Public helpers callable from runtime-generated types. Nested type so it can
    // access Bridge's private proxy helpers (ProxyInvokeMethod, etc.) while
    // exposing a stable public API for emitted proxies.
    public static class ProxyRuntime
    {
        public static T InvokeMethodTyped<T>(object instance, string methodName, object[] args)
        {
            var result = ProxyInvokeMethod(instance, methodName, args);
            if (result is null) return default!;
            if (result is T t) return t;
            return (T)Convert.ChangeType(result, typeof(T), CultureInfo.InvariantCulture);
        }

        public static object? InvokeMethod(object instance, string methodName, object[] args)
        {
            return ProxyInvokeMethod(instance, methodName, args);
        }

        public static void InvokeVoid(object instance, string methodName, object[] args)
        {
            ProxyInvokeVoid(instance, methodName, args);
        }

        public static T GetProperty<T>(object instance, string propertyName)
        {
            var result = ProxyGetProperty(instance, propertyName);
            if (result is null) return default!;
            if (result is T t) return t;
            return (T)Convert.ChangeType(result, typeof(T), CultureInfo.InvariantCulture);
        }

        public static void SetProperty(object instance, string propertyName, object? value)
        {
            ProxySetProperty(instance, propertyName, value);
        }
    }
    private sealed class ProxyCallbackHolder { public int CallbackId; public int HandleId; public ProxyCallbackHolder(int cb) { CallbackId = cb; HandleId = 0; } }

    private static readonly ConditionalWeakTable<object, ProxyCallbackHolder> s_proxyCallbacks = new();
    private static readonly ThreadLocal<int?> s_pendingProxyCallbackId = new(() => null);
    private static readonly object s_proxyRegisterLock = new();
    private static bool s_proxyDispatcherRegistered = false;

    private static void EnsureProxyDispatcherCallbacksRegistered()
    {
        if (s_proxyDispatcherRegistered) return;
        lock (s_proxyRegisterLock)
        {
            if (s_proxyDispatcherRegistered) return;

            Type? pdType = null;
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    pdType = asm.GetType("NativeScriptGeneratedProxies.ProxyDispatcher")
                          ?? asm.GetType("NSWinRTProxies.ProxyDispatcher")
                          ?? asm.GetType("NativeScriptGeneratedProxies.ProxyDispatcher");
                    if (pdType != null) break;
                }
                catch { }
            }

            if (pdType != null)
            {
                // Properties generated by SBG
                var p1 = pdType.GetProperty("JsInvokeMethod", BindingFlags.Public | BindingFlags.Static);
                p1?.SetValue(null, new Func<object, string, object[], object?>(ProxyInvokeMethod));

                var p2 = pdType.GetProperty("JsInvokeVoid", BindingFlags.Public | BindingFlags.Static);
                p2?.SetValue(null, new Action<object, string, object[]>(ProxyInvokeVoid));

                var p3 = pdType.GetProperty("JsGetProperty", BindingFlags.Public | BindingFlags.Static);
                p3?.SetValue(null, new Func<object, string, object?>(ProxyGetProperty));

                var p4 = pdType.GetProperty("JsSetProperty", BindingFlags.Public | BindingFlags.Static);
                p4?.SetValue(null, new Action<object, string, object?>(ProxySetProperty));

                var p5 = pdType.GetProperty("JsInitializeInstance", BindingFlags.Public | BindingFlags.Static);
                p5?.SetValue(null, new Action<object, string>(ProxyInitializeInstance));
            }

            s_proxyDispatcherRegistered = true;
        }
    }

    private static bool DynamicProxiesEnabled()
    {
        // Always allow dynamic proxies in dev when Reflection.Emit is available.
        return s_dynamicModule != null;
    }

    private static Type? FindGeneratedProxyType(string typeName)
    {
        if (string.IsNullOrEmpty(typeName)) return null;
        var lastDot = typeName.LastIndexOf('.');
        var shortName = lastDot >= 0 ? typeName[(lastDot + 1)..] : typeName;
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            try
            {
                // Only consider assemblies that look like generated proxy assemblies
                var asmName = asm.GetName().Name ?? "";
                if (!string.Equals(asmName, "NativeScriptGeneratedProxies", StringComparison.Ordinal)
                    && !string.Equals(asmName, "NSWinRTProxies", StringComparison.Ordinal))
                {
                    // Also check for candidate full-type names in any assembly
                    var candidates = new[] { $"NativeScriptGeneratedProxies.{shortName}", $"NSWinRTProxies.{shortName}" };
                    foreach (var cn in candidates)
                    {
                        var t = asm.GetType(cn);
                        if (t is not null) return t;
                    }
                    continue;
                }

                // If this is a generated proxies assembly, look up the proxy type name.
                var genCandidates = new[] { $"NativeScriptGeneratedProxies.{shortName}", $"NSWinRTProxies.{shortName}" };
                foreach (var cn in genCandidates)
                {
                    var t = asm.GetType(cn);
                    if (t is not null) return t;
                }
            }
            catch { }
        }
        return null;
    }

    private static Type GetOrCreateDynamicProxyType(Type baseType)
    {
        return s_dynamicProxyCache.GetOrAdd(baseType, bt => CreateDynamicProxyType(bt));
    }

    private static Type CreateDynamicProxyType(Type baseType)
    {
        
        if (s_dynamicModule == null)
            throw new InvalidOperationException("Dynamic proxy generation not available in this environment");

        if (baseType.IsSealed)
            throw new InvalidOperationException($"Cannot derive from sealed type {baseType.FullName}");

        var safeName = (baseType.FullName ?? Guid.NewGuid().ToString()).Replace('.', '_');
        var typeName = $"NSWinRTDynamicProxies.{safeName}_JsProxy";

        var tb = s_dynamicModule.DefineType(typeName, TypeAttributes.Public | TypeAttributes.Class, baseType);

        // Mirror public base constructors and ensure at least a parameterless
        // ctor exists on the derived type. If the base type has no parameterless
        // ctor, emit a parameterless ctor that forwards default(T) values to the
        // first available base ctor (dev-only convenience).
        var baseCtors = baseType.GetConstructors(BindingFlags.Public | BindingFlags.Instance)
                        .Where(c => !c.IsGenericMethod)
                        .ToArray();

        ConstructorInfo? chosenBaseForDefault = null;
        foreach (var bc in baseCtors)
        {
            var parameters = bc.GetParameters();
            if (parameters.Any(p => p.ParameterType.IsByRef)) continue;
            chosenBaseForDefault ??= bc;

            // Define a matching ctor on the derived type that forwards args to base.
            var paramTypes = parameters.Select(p => p.ParameterType).ToArray();
            var derivedCtor = tb.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, paramTypes);
            var ilg = derivedCtor.GetILGenerator();
            // Load 'this'
            ilg.Emit(OpCodes.Ldarg_0);
            // Load each argument and forward
            for (int i = 0; i < paramTypes.Length; i++)
            {
                // ldarg_1..n
                switch (i + 1)
                {
                    case 1: ilg.Emit(OpCodes.Ldarg_1); break;
                    case 2: ilg.Emit(OpCodes.Ldarg_2); break;
                    case 3: ilg.Emit(OpCodes.Ldarg_3); break;
                    default: ilg.Emit(OpCodes.Ldarg, i + 1); break;
                }
            }
            ilg.Emit(OpCodes.Call, bc);
            ilg.Emit(OpCodes.Ret);
        }

        // If we didn't define a parameterless ctor, emit one that forwards
        // default(T) values to the chosen base ctor (if any), otherwise call
        // System.Object..ctor.
        if (!baseCtors.Any(c => c.GetParameters().Length == 0))
        {
            var paramless = tb.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, Type.EmptyTypes);
            var ilg = paramless.GetILGenerator();
            if (chosenBaseForDefault is not null)
            {
                ilg.Emit(OpCodes.Ldarg_0);
                var parameters = chosenBaseForDefault.GetParameters();
                // For each param, emit default value (null for ref types, initobj local for value types)
                for (int i = 0; i < parameters.Length; i++)
                {
                    var ptype = parameters[i].ParameterType;
                    if (ptype.IsByRef) throw new InvalidOperationException("Cannot forward byref parameters in dynamic ctor");
                    if (ptype.IsValueType)
                    {
                        var temp = ilg.DeclareLocal(ptype);
                        ilg.Emit(OpCodes.Ldloca_S, temp);
                        ilg.Emit(OpCodes.Initobj, ptype);
                        ilg.Emit(OpCodes.Ldloc, temp);
                    }
                    else
                    {
                        ilg.Emit(OpCodes.Ldnull);
                    }
                }
                ilg.Emit(OpCodes.Call, chosenBaseForDefault);
                ilg.Emit(OpCodes.Ret);
            }
            else
            {
                // No public base ctors (rare); call Object..ctor
                var objCtor = typeof(object).GetConstructor(Type.EmptyTypes)!;
                ilg.Emit(OpCodes.Ldarg_0);
                ilg.Emit(OpCodes.Call, objCtor);
                ilg.Emit(OpCodes.Ret);
            }
        }

        // Override all non-final virtual instance methods (skip ref/out and generic methods)
        var methods = baseType.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
            .Where(m => m.IsVirtual && !m.IsFinal && !m.IsGenericMethod && !m.IsConstructor)
            .ToArray();

        foreach (var mi in methods)
        {
            var parameters = mi.GetParameters();
            if (parameters.Any(p => p.ParameterType.IsByRef)) continue;

            var paramTypes = parameters.Select(p => p.ParameterType).ToArray();
            var mb = tb.DefineMethod(mi.Name,
                MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig,
                mi.CallingConvention, mi.ReturnType, paramTypes);

            var ilg = mb.GetILGenerator();
            var argsLocal = ilg.DeclareLocal(typeof(object[]));
            ilg.Emit(OpCodes.Ldc_I4, paramTypes.Length);
            ilg.Emit(OpCodes.Newarr, typeof(object));
            ilg.Emit(OpCodes.Stloc, argsLocal);

            for (int i = 0; i < paramTypes.Length; i++)
            {
                ilg.Emit(OpCodes.Ldloc, argsLocal);
                ilg.Emit(OpCodes.Ldc_I4, i);
                ilg.Emit(OpCodes.Ldarg, i + 1);
                if (paramTypes[i].IsValueType) ilg.Emit(OpCodes.Box, paramTypes[i]);
                ilg.Emit(OpCodes.Stelem_Ref);
            }

            if (mi.ReturnType == typeof(void))
            {
                var invokeVoid = typeof(Bridge).GetNestedType("ProxyRuntime", BindingFlags.Public | BindingFlags.Static)!.GetMethod("InvokeVoid", BindingFlags.Public | BindingFlags.Static)!;
                ilg.Emit(OpCodes.Ldarg_0);
                ilg.Emit(OpCodes.Ldstr, mi.Name);
                ilg.Emit(OpCodes.Ldloc, argsLocal);
                ilg.Emit(OpCodes.Call, invokeVoid);
                ilg.Emit(OpCodes.Ret);
            }
            else
            {
                var proxyRuntimeType = typeof(Bridge).GetNestedType("ProxyRuntime", BindingFlags.Public | BindingFlags.Static)!;
                var gm = proxyRuntimeType.GetMethod("InvokeMethodTyped", BindingFlags.Public | BindingFlags.Static)!.MakeGenericMethod(mi.ReturnType);
                ilg.Emit(OpCodes.Ldarg_0);
                ilg.Emit(OpCodes.Ldstr, mi.Name);
                ilg.Emit(OpCodes.Ldloc, argsLocal);
                ilg.Emit(OpCodes.Call, gm);
                ilg.Emit(OpCodes.Ret);
            }

            tb.DefineMethodOverride(mb, mi);
        }

        return tb.CreateTypeInfo()!.AsType();
    }

    private static DispatchResult CreateJsSubclass(string? assemblyName, string typeName, int callbackId)
    {
        EnsureProxyDispatcherCallbacksRegistered();

        s_pendingProxyCallbackId.Value = callbackId;

        // Try to find a statically-generated proxy type first.
        Type? t = FindGeneratedProxyType(typeName);
        if (t is null)
        {
            // Resolve the WinRT/base type and optionally emit a dynamic proxy (dev-only).
            var baseType = ResolveType(assemblyName, typeName) ?? throw new TypeLoadException($"Type not found: {typeName} (assembly: {assemblyName})");
            
            if (baseType.IsClass && !baseType.IsSealed)
            {
                try { t = GetOrCreateDynamicProxyType(baseType); }
                catch (Exception) { t = baseType; }
            }
            else
            {
                t = baseType;
            }
        }

        // Create the managed instance. Generated classes should call
        // ProxyDispatcher.InitializeInstance(this, typeName) in their constructor,
        // which will invoke our ProxyInitializeInstance and capture the pending callback id.
        var instance = Activator.CreateInstance(t) ?? throw new InvalidOperationException("Failed to instantiate proxy type.");

        // Ensure there's a mapping for this instance immediately to avoid any
        // early virtual calls from constructors reaching the JS side before
        // the handle is registered. Call our initializer directly to register
        // the pending callback id when dynamic proxies don't call it.
        try { ProxyInitializeInstance(instance, typeName); } catch { }

        // Box the instance into a handle to return to the runtime.
        var result = Box(instance);

        // Populate holder with handle id now that a handle exists.
        if (s_proxyCallbacks.TryGetValue(instance, out var holder))
        {
            try { holder.HandleId = result.HandleId(); } catch { holder.HandleId = 0; }
        }
        else
        {
            // If the generated proxy did not call InitializeInstance, create mapping now.
            int hid = 0;
            try { hid = result.HandleId(); } catch { hid = 0; }
            var newHolder = new ProxyCallbackHolder(callbackId) { HandleId = hid };
            s_proxyCallbacks.Add(instance, newHolder);
        }

        s_pendingProxyCallbackId.Value = null;
        return result;
    }

    private static void ProxyInitializeInstance(object instance, string typeName)
    {
        var cb = s_pendingProxyCallbackId.Value;
        if (cb.HasValue)
        {
            var holder = new ProxyCallbackHolder(cb.Value);
            s_proxyCallbacks.Add(instance, holder);
        }
    }

    private static object? ProxyInvokeMethod(object instance, string methodName, object[] args)
    {
        if (!s_proxyCallbacks.TryGetValue(instance, out var holder)) throw new InvalidOperationException("No JS callback registered for proxy instance.");
        var payload = new object?[] { new HandleRef(holder.HandleId), methodName, args };
        return CallJsCallback(holder.CallbackId, payload);
    }

    private static void ProxyInvokeVoid(object instance, string methodName, object[] args)
    {
        if (!s_proxyCallbacks.TryGetValue(instance, out var holder)) throw new InvalidOperationException("No JS callback registered for proxy instance.");
        
        var payload = new object?[] { new HandleRef(holder.HandleId), methodName, args };
        CallJsCallback(holder.CallbackId, payload);
    }

    private static object? ProxyGetProperty(object instance, string propertyName)
    {
        if (!s_proxyCallbacks.TryGetValue(instance, out var holder)) throw new InvalidOperationException("No JS callback registered for proxy instance.");
        var payload = new object?[] { new HandleRef(holder.HandleId), propertyName };
        CallJsCallback(holder.CallbackId, payload);
        return null;
    }

    private static void ProxySetProperty(object instance, string propertyName, object? value)
    {
        if (!s_proxyCallbacks.TryGetValue(instance, out var holder)) throw new InvalidOperationException("No JS callback registered for proxy instance.");
        var payload = new object?[] { new HandleRef(holder.HandleId), propertyName, value };
        CallJsCallback(holder.CallbackId, payload);
    }
}

