[package]
name = "core"
version = "0.1.0"
edition = "2018"

[lib]
name = "nativescript"
crate-type = ["dylib"]


[dependencies]
windows = "0.13.0"
rusty_v8 = "0.23.0"
core_bindings = { package = "core_bindings", path = "../core-bindings" }
chrono = "0.4.19"
libc = "0.2.97"
lazy_static = "1.4.0"
