/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Format one value exactly as `console.log` (rich=false) or `console.dir` (rich=true) would. */
export declare function formatValue(value: unknown, rich: boolean): string
/** Render `console.table` output for a value (optional column filter). */
export declare function tableFor(value: unknown, columns?: Array<string> | undefined | null): string
/**
 * Wrap `func` in a NapiDelegate COM object with the given Invoke parameter types.
 * Returns the COM pointer as f64 (refcount 1).
 */
export declare function makeDelegate(func: (...args: any[]) => any, paramTypes: Array<string>): number
/**
 * Fire the delegate through its COM vtable with up to three raw (usize-packed) args.
 * Returns the HRESULT.
 */
export declare function invokeDelegate(ptr: number, p0: number, p1: number, p2: number): number
/** Release one COM reference; returns the remaining count. */
export declare function releaseDelegate(ptr: number): number
/**
 * Call a static WinRT method: `callStaticMethod('Windows.Data.Json.JsonValue',
 * 'CreateStringValue', ['hello'])`.
 */
export declare function callStaticMethod(className: string, methodName: string, args: Array<unknown>): unknown
/** Call an instance WinRT method on a pointer external returned by a previous call. */
export declare function callInstanceMethod(instance: unknown, className: string, methodName: string, args: Array<unknown>): unknown
/**
 * Build a native-backed JS `Proxy`. Reads/writes flow through Rust trap callbacks into a
 * shared native map — the exact shape `ns_proxy.rs` will take under Node-API.
 */
export declare function makeNativeProxy(): object
/**
 * Parse `value` as `ty` into a `NativeValue`, then marshal it back to JS. Throws on parse
 * errors so the JS test can assert rejection.
 */
export declare function ffiRoundtrip(value: unknown, ty: string): unknown
/**
 * Parse `value` as a Pointer arg and return the raw pointer as f64 (user-space addresses
 * fit in 2^53).
 */
export declare function pointerValue(value: unknown): number
/** Create a native-pointer external carrying `addr` (for pointer round-trip tests). */
export declare function makeExternal(addr: number): unknown
/** Parse `value` as a Buffer arg; returns `[dataPtr, byteLength]` as f64s. */
export declare function bufferInfo(value: unknown): Array<number>
/** Parse `value` as a Struct arg; returns the data pointer as f64. */
export declare function structPtr(value: unknown): number
/**
 * Write `value` into a native scratch slot as `ty`, then read it back to JS — exercises
 * `write_js_value_to_ptr` + `read_value_from_ptr` (including HSTRING ownership hand-off).
 */
export declare function writeReadPtr(value: unknown, ty: string): unknown
/**
 * If `value` is an `interop.out(...)` wrapper, return its wrapped value; else return the
 * string `"<none>"`.
 */
export declare function outParamValue(value: unknown): unknown
/** Set the `value` slot of an out-param wrapper; returns whether the set succeeded. */
export declare function setOutParam(wrapper: object, newValue: unknown): boolean
/** Serialize `value` as a struct field of type `ty`; returns the little-endian bytes. */
export declare function structFieldBytes(value: unknown, ty: string): Array<number>
/**
 * Box `value` as a WinRT `IPropertyValue` of `ty`; returns the raw IInspectable pointer as
 * f64 (0 when boxing is not possible). Requires WinRT initialized (call init() first).
 */
export declare function boxTyped(value: unknown, ty: string): number
/**
 * Create the runtime rooted at `appRoot` (defaults to the empty string). Idempotent: a second
 * call while a runtime already exists is a no-op and returns `true`.
 */
export declare function init(appRoot?: string | undefined | null): boolean
/** Evaluate `script` under `filename` (defaults to `main.js`) in the runtime's context. */
export declare function runScript(script: string, filename?: string | undefined | null): void
/**
 * Drain JS timers and pump the appropriate message/dispatcher loop for one tick. Wire this to
 * a libuv `check`/`prepare` handle (or an `setImmediate` loop) so `setTimeout`, WinRT async
 * `Completed` callbacks, and their promise continuations fire.
 */
export declare function pumpTimers(): void
/** Pump Win32 messages and flush microtasks. Returns `true` if a message was dispatched. */
export declare function pumpMessages(): boolean
/** The last JS error (message + stack), if any. */
export declare function lastError(): string | null
/**
 * Install the runtime's globals (`__time`, and `performance`/`console` where the host lacks
 * them) onto the host's global object.
 */
export declare function installGlobals(): void
/**
 * Resolve a WinRT namespace root (e.g. `getNamespace('Windows')`) as a lazy proxy: member
 * access walks metadata, classes come back as constructable proxies.
 */
export declare function getNamespace(name: string): object
/** Generate a fresh UUID string (CoCreateGuid). */
export declare function nsUuid(): string
/**
 * Whether the WinRT class `name` is sealed (metadata flag). Test hook: lets suites assert
 * they are really covering the composable (non-sealed, null-outer) constructor path.
 */
export declare function classIsSealed(name: string): boolean | null
/** Register a third-party `.winmd` file for metadata resolution (WebView2, app types, …). */
export declare function registerWinmd(path: string): void
/** Register every `.winmd` in a directory (non-recursive); returns the count registered. */
export declare function scanWinmdDir(dir: string): number
/** Wrap a `Windows.Storage.Streams.IBuffer` as a (zero-copy where supported) ArrayBuffer. */
export declare function arrayBufferFromBuffer(buffer: unknown): unknown
/**
 * Install the `__ns*` interop natives and the `NSWinRT.interop` JS surface (Pointer/OutParam,
 * `reference` / typed-value boxing, buffer + DateTime utilities) without touching any other
 * host global. Idempotent; `nswinrt.js` calls this on load.
 */
export declare function installInterop(): void
/**
 * Install the `.NET`/BCL bridge natives and the `NSWinRT.dotnet` JS surface
 * (invoke/get/fromHandle/registerNamespace, taskToPromise/asDelegate, `NSWinRT.runOnUIThread`).
 * Idempotent; `nswinrt.js` calls this on load. A no-op at the JS layer until a
 * `dotnet-bridge/publish/DotNetBridge.dll` exists next to the app.
 */
export declare function installDotnet(): void
/** Tear the runtime down on this thread. */
export declare function deinit(): void
