/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'windows.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.android-arm64.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'windows.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.android-arm-eabi.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'windows.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'windows.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'windows.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'windows.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./windows.darwin-universal.node')
      } else {
        nativeBinding = require('@nativescript/windows-napi-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'windows.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.darwin-x64.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'windows.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.darwin-arm64.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'windows.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./windows.freebsd-x64.node')
      } else {
        nativeBinding = require('@nativescript/windows-napi-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-x64-musl.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'windows.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./windows.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@nativescript/windows-napi-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'windows.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./windows.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@nativescript/windows-napi-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { formatValue, tableFor, makeDelegate, invokeDelegate, releaseDelegate, callStaticMethod, callInstanceMethod, makeNativeProxy, ffiRoundtrip, pointerValue, makeExternal, bufferInfo, structPtr, writeReadPtr, outParamValue, setOutParam, structFieldBytes, boxTyped, init, runScript, pumpTimers, pumpMessages, lastError, installGlobals, getNamespace, nsUuid, classIsSealed, registerWinmd, scanWinmdDir, arrayBufferFromBuffer, installInterop, installDotnet, deinit } = nativeBinding

module.exports.formatValue = formatValue
module.exports.tableFor = tableFor
module.exports.makeDelegate = makeDelegate
module.exports.invokeDelegate = invokeDelegate
module.exports.releaseDelegate = releaseDelegate
module.exports.callStaticMethod = callStaticMethod
module.exports.callInstanceMethod = callInstanceMethod
module.exports.makeNativeProxy = makeNativeProxy
module.exports.ffiRoundtrip = ffiRoundtrip
module.exports.pointerValue = pointerValue
module.exports.makeExternal = makeExternal
module.exports.bufferInfo = bufferInfo
module.exports.structPtr = structPtr
module.exports.writeReadPtr = writeReadPtr
module.exports.outParamValue = outParamValue
module.exports.setOutParam = setOutParam
module.exports.structFieldBytes = structFieldBytes
module.exports.boxTyped = boxTyped
module.exports.init = init
module.exports.runScript = runScript
module.exports.pumpTimers = pumpTimers
module.exports.pumpMessages = pumpMessages
module.exports.lastError = lastError
module.exports.installGlobals = installGlobals
module.exports.getNamespace = getNamespace
module.exports.nsUuid = nsUuid
module.exports.classIsSealed = classIsSealed
module.exports.registerWinmd = registerWinmd
module.exports.scanWinmdDir = scanWinmdDir
module.exports.arrayBufferFromBuffer = arrayBufferFromBuffer
module.exports.installInterop = installInterop
module.exports.installDotnet = installDotnet
module.exports.deinit = deinit
