// dotnet-typings-gen — emit TypeScript declarations from a .NET DLL or .csproj.
//
// Usage:
//   dotnet run --project dotnet-typings-gen.csproj -- \
//       --input  NativeScript.Widgets.dll \
//       --root   NativeScript             \
//       --out    NativeScript.Widgets.d.ts
//
// --input  Path to a .dll or .csproj (builds the project first if .csproj).
// --root   Namespace prefix to include (optional — all public types if omitted).
// --out    Output .d.ts file path.

using System.Collections.Immutable;
using System.Diagnostics;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;

return Generator.Run(args);

// ═══════════════════════════════════════════════════════════════════════════════

static class Generator
{
    public static int Run(string[] args)
    {
        string? inputPath = null, outPath = null, rootNs = null;
        for (int i = 0; i < args.Length; i++)
            switch (args[i])
            {
                case "--input": inputPath = args[++i]; break;
                case "--out":   outPath   = args[++i]; break;
                case "--root":  rootNs    = args[++i]; break;
            }

        if (inputPath == null || outPath == null)
        {
            Console.Error.WriteLine("Usage: dotnet-typings-gen --input <dll|csproj> [--root <ns>] --out <file>");
            return 1;
        }

        if (inputPath.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase))
        {
            inputPath = BuildCsProj(inputPath);
            if (inputPath == null) return 1;
        }

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"[typings-gen] Input not found: {inputPath}");
            return 1;
        }

        using var fs     = File.OpenRead(inputPath);
        using var pe     = new PEReader(fs);
        var       reader = pe.GetMetadataReader();
        var       dec    = new TsTypeDecoder(reader);

        var modules = new SortedDictionary<string, List<string>>(StringComparer.Ordinal);

        foreach (var typeHandle in reader.TypeDefinitions)
        {
            var typeDef = reader.GetTypeDefinition(typeHandle);
            var vis     = typeDef.Attributes & TypeAttributes.VisibilityMask;
            if (vis != TypeAttributes.Public && vis != TypeAttributes.NestedPublic) continue;

            var ns       = reader.GetString(typeDef.Namespace);
            var name     = reader.GetString(typeDef.Name);
            var fullName = Helpers.FullName(ns, name);

            if (rootNs != null
                && !fullName.Equals(rootNs, StringComparison.Ordinal)
                && !fullName.StartsWith(rootNs + ".", StringComparison.Ordinal)) continue;

            var decl = EmitTypeDecl(reader, dec, typeDef, name);
            if (decl == null) continue;

            if (!modules.TryGetValue(ns, out var list))
                modules[ns] = list = [];
            list.Add(decl);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by typings-generator (dotnet mode).");
        sb.AppendLine("// Do not edit - re-run build.windows.ps1 to regenerate.");
        sb.AppendLine();
        sb.AppendLine("export {};");
        sb.AppendLine();
        sb.AppendLine("declare global {");
        foreach (var (ns, decls) in modules)
        {
            sb.AppendLine($"  namespace {ns} {{");
            foreach (var d in decls) sb.AppendLine(d);
            sb.AppendLine("  }");
        }
        sb.AppendLine("}");

        var dir = Path.GetDirectoryName(outPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        int total = modules.Values.Sum(v => v.Count);
        Console.WriteLine($"[typings-gen] {total} type(s) → {outPath}");
        return 0;
    }

    static string? BuildCsProj(string csprojPath)
    {
        var psi = new ProcessStartInfo("dotnet",
            $"build \"{csprojPath}\" -c Release --verbosity minimal --nologo")
        {
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
        };
        using var proc = Process.Start(psi)!;
        string stdout = proc.StandardOutput.ReadToEnd();
        string stderr = proc.StandardError.ReadToEnd();
        proc.WaitForExit();

        if (proc.ExitCode != 0)
        {
            Console.Error.WriteLine($"[typings-gen] Build failed:\n{stderr}");
            return null;
        }

        foreach (var line in stdout.Split('\n'))
        {
            int arrow = line.IndexOf("->", StringComparison.Ordinal);
            if (arrow < 0) continue;
            var dll = line[(arrow + 2)..].Trim();
            if (dll.EndsWith(".dll", StringComparison.OrdinalIgnoreCase) && File.Exists(dll))
                return dll;
        }

        Console.Error.WriteLine("[typings-gen] Could not locate output DLL in build log.");
        return null;
    }

    static string? EmitTypeDecl(MetadataReader reader, TsTypeDecoder dec,
                                 TypeDefinition typeDef, string simpleName)
    {
        bool isIface = (typeDef.Attributes & TypeAttributes.Interface) != 0;
        string kw    = isIface ? "interface" : "class";

        string extendsClause = "";
        if (!isIface && !typeDef.BaseType.IsNil)
        {
            string baseName = Helpers.ResolveEntityName(reader, typeDef.BaseType);
            if (!string.IsNullOrEmpty(baseName) && baseName != "System.Object")
                extendsClause = $" extends {Helpers.MapBuiltinType(baseName)}";
        }

        var sb = new StringBuilder();
        sb.AppendLine($"    {kw} {simpleName}{extendsClause} {{");

        var accessors = CollectPropertyAccessors(reader, typeDef);

        // Public fields (e.g. static readonly DependencyProperty FooProperty)
        foreach (var fieldHandle in typeDef.GetFields())
        {
            var field = reader.GetFieldDefinition(fieldHandle);
            if ((field.Attributes & FieldAttributes.FieldAccessMask) != FieldAttributes.Public) continue;

            string fName  = reader.GetString(field.Name);
            bool   fStat  = (field.Attributes & FieldAttributes.Static) != 0;
            bool   fRo    = (field.Attributes & FieldAttributes.InitOnly) != 0;
            string fType;
            try   { fType = field.DecodeSignature(dec, null); }
            catch { continue; }

            sb.AppendLine($"      {(fStat ? "static " : "")}{(fRo ? "readonly " : "")}{fName}: {fType};");
        }

        // Public properties
        foreach (var propHandle in typeDef.GetProperties())
        {
            var prop = reader.GetPropertyDefinition(propHandle);
            var acc  = prop.GetAccessors();
            if (acc.Getter.IsNil) continue;

            var getter = reader.GetMethodDefinition(acc.Getter);
            // Skip non-public properties (e.g. private helper properties)
            if ((getter.Attributes & MethodAttributes.MemberAccessMask) != MethodAttributes.Public) continue;

            bool stat    = (getter.Attributes & MethodAttributes.Static) != 0;
            bool ro      = acc.Setter.IsNil;
            string pName = reader.GetString(prop.Name);
            MethodSignature<string> sig;
            try   { sig = prop.DecodeSignature(dec, null); }
            catch { continue; }

            sb.AppendLine($"      {(stat ? "static " : "")}{(ro ? "readonly " : "")}{pName}: {sig.ReturnType};");
        }

        foreach (var methodHandle in typeDef.GetMethods())
        {
            if (accessors.Contains(methodHandle)) continue;
            var method = reader.GetMethodDefinition(methodHandle);
            if ((method.Attributes & MethodAttributes.MemberAccessMask) != MethodAttributes.Public) continue;

            string mName = reader.GetString(method.Name);
            if (mName.StartsWith('.')) continue;

            bool isStatic = (method.Attributes & MethodAttributes.Static) != 0;
            MethodSignature<string> sig;
            try   { sig = method.DecodeSignature(dec, null); }
            catch { continue; }

            var paramHandles = method.GetParameters().ToArray();
            var paramStrs    = new List<string>();
            for (int i = 0; i < sig.ParameterTypes.Length; i++)
            {
                string pn = "p" + i;
                if (i < paramHandles.Length)
                {
                    var candidate = reader.GetString(reader.GetParameter(paramHandles[i]).Name);
                    if (!string.IsNullOrWhiteSpace(candidate)) pn = candidate;
                }
                paramStrs.Add($"{pn}: {sig.ParameterTypes[i]}");
            }

            sb.AppendLine($"      {(isStatic ? "static " : "")}{mName}({string.Join(", ", paramStrs)}): {sig.ReturnType};");
        }

        sb.Append("    }");
        return sb.ToString();
    }

    static HashSet<MethodDefinitionHandle> CollectPropertyAccessors(MetadataReader reader, TypeDefinition typeDef)
    {
        var set = new HashSet<MethodDefinitionHandle>();
        foreach (var propHandle in typeDef.GetProperties())
        {
            var acc = reader.GetPropertyDefinition(propHandle).GetAccessors();
            if (!acc.Getter.IsNil) set.Add(acc.Getter);
            if (!acc.Setter.IsNil) set.Add(acc.Setter);
        }
        return set;
    }
}

// ═══════════════════════════════════════════════════════════════════════════════

static class Helpers
{
    public static string FullName(string ns, string name)
        => string.IsNullOrEmpty(ns) ? name : $"{ns}.{name}";

    public static string ResolveEntityName(MetadataReader reader, EntityHandle handle)
    {
        if (handle.IsNil) return string.Empty;
        if (handle.Kind == HandleKind.TypeDefinition)
        {
            var td = reader.GetTypeDefinition((TypeDefinitionHandle)handle);
            return FullName(reader.GetString(td.Namespace), reader.GetString(td.Name));
        }
        if (handle.Kind == HandleKind.TypeReference)
        {
            var tr = reader.GetTypeReference((TypeReferenceHandle)handle);
            return FullName(reader.GetString(tr.Namespace), reader.GetString(tr.Name));
        }
        return string.Empty;
    }

    public static string MapBuiltinType(string name) => name switch
    {
        "System.Boolean"               => "boolean",
        "System.String" or "System.Char" => "string",
        "System.Byte"   or "System.SByte"
            or "System.Int16"  or "System.UInt16"
            or "System.Int32"  or "System.UInt32"
            or "System.Int64"  or "System.UInt64"
            or "System.Single" or "System.Double"
            or "System.IntPtr" or "System.UIntPtr" => "number",
        "System.Object" => "any",
        "System.Void"   => "void",
        _               => name,
    };
}

// ═══════════════════════════════════════════════════════════════════════════════

class TsTypeDecoder : ISignatureTypeProvider<string, object?>
{
    private readonly MetadataReader _r;
    public TsTypeDecoder(MetadataReader r) => _r = r;

    public string GetPrimitiveType(PrimitiveTypeCode code) => code switch
    {
        PrimitiveTypeCode.Void    => "void",
        PrimitiveTypeCode.Boolean => "boolean",
        PrimitiveTypeCode.Char    => "string",
        PrimitiveTypeCode.String  => "string",
        PrimitiveTypeCode.Object  => "any",
        PrimitiveTypeCode.SByte   or PrimitiveTypeCode.Byte
            or PrimitiveTypeCode.Int16  or PrimitiveTypeCode.UInt16
            or PrimitiveTypeCode.Int32  or PrimitiveTypeCode.UInt32
            or PrimitiveTypeCode.Int64  or PrimitiveTypeCode.UInt64
            or PrimitiveTypeCode.Single or PrimitiveTypeCode.Double
            or PrimitiveTypeCode.IntPtr or PrimitiveTypeCode.UIntPtr => "number",
        _ => "any",
    };

    public string GetTypeFromDefinition(MetadataReader r, TypeDefinitionHandle h, byte _)
    {
        var td = r.GetTypeDefinition(h);
        return Helpers.MapBuiltinType(Helpers.FullName(r.GetString(td.Namespace), r.GetString(td.Name)));
    }

    public string GetTypeFromReference(MetadataReader r, TypeReferenceHandle h, byte _)
    {
        var tr = r.GetTypeReference(h);
        return Helpers.MapBuiltinType(Helpers.FullName(r.GetString(tr.Namespace), r.GetString(tr.Name)));
    }

    public string GetTypeFromSpecification(MetadataReader r, object? ctx, TypeSpecificationHandle h, byte _)
        => r.GetTypeSpecification(h).DecodeSignature(this, ctx);

    public string GetSZArrayType(string elem)                           => $"{elem}[]";
    public string GetArrayType(string elem, ArrayShape _)               => $"{elem}[]";
    public string GetByReferenceType(string elem)                       => elem;
    public string GetPointerType(string _)                              => "any";
    public string GetPinnedType(string elem)                            => elem;
    public string GetModifiedType(string _, string unmodified, bool __) => unmodified;
    public string GetFunctionPointerType(MethodSignature<string> _)     => "Function";
    public string GetGenericMethodParameter(object? _, int index)       => $"T{index}";
    public string GetGenericTypeParameter(object? _, int index)         => $"T{index}";
    public string GetGenericInstantiation(string generic, ImmutableArray<string> typeArgs)
        => $"{generic}<{string.Join(", ", typeArgs)}>";
}
