[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
metadata = { path = "../metadata" }
nativescript = { path = "../nativescript" }

[dependencies.windows]
workspace = true
features = [
    "Foundation",
    "Foundation_Collections",
    "Foundation_Numerics",
    "System",
    "Win32_Foundation",
    "Win32_System_WinRT",
    "Win32_UI_WindowsAndMessaging",
]