<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>NativeScriptWindowsDemo</RootNamespace>
    <AssemblyName>NativeScriptWindowsDemo</AssemblyName>
    <UseUwp>true</UseUwp>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>en-US</DefaultLanguage>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateAppInstallerFile>false</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <PublishProfile>win-x86.pubxml</PublishProfile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <PublishProfile>win-x64.pubxml</PublishProfile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|arm64'">
    <PublishProfile>win-arm64.pubxml</PublishProfile>
  </PropertyGroup>

  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest" />
    <Content Include="Properties\Default.rd.xml" />

    <Content Update="App\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="libs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>